### ISSUE TITLE
docker-compose exited with code 132

### ISSUE THREAD

**Issue by michelelaporta** [ShubhamTatvamasi/srsRAN-demo#2]
I'm trying to build:

magma@srsra:~/srsRAN-demo$ docker-compose up
Pulling srsenb (shubhamtatvamasi/srsran-demo:)...
latest: Pulling from shubhamtatvamasi/srsran-demo
7b1a6ab2e44d: Pull complete
ec7a22b6ee5a: Pull complete
3a19e7e3f593: Pull complete
a88b025eab75: Pull complete
e57125f9857f: Pull complete
fef5f8f2bda5: Pull complete
b4d3bd4d9e98: Pull complete
a03653eb33f7: Pull complete
a16327d0778a: Pull complete
Digest: sha256:194690fa9ccde42d90bdc8a5399cca3e458d543be4cd9ca280d20725539ef476
Status: Downloaded newer image for shubhamtatvamasi/srsran-demo:latest
Creating srsenb ... done
Creating srsue  ... done
Attaching to srsenb, srsue
srsenb exited with code 132
srsue exited with code 132

Also

magma@srsra:~/srsRAN-demo$ docker run -it shubhamtatvamasi/srsran-demo /bin/bash
root@cff8062be17d:/etc/srsran# srsenb
Illegal instruction (core dumped)

root@cff8062be17d:/etc/srsran# srsue
Illegal instruction (core dumped)

maybe the image is corrupted?

Any advice?

Thanks 

Michele

**Comment by ShubhamTatvamasi** [comment]
Hi Michele, You need to build docker image again on your hardware then only it will work.

**Comment by michelelaporta** [comment]
With rebuild now it works thanks.
