### ISSUE TITLE
debug with tcpdump 

### ISSUE THREAD

**Issue by michelelaporta** [ShubhamTatvamasi/srsRAN-demo#3]
Hi Shubham,
I would like to know how to use tcpdump in order to analyze traffic. My setup:

* baremetal with:
   * vagrant agw
   * vagrant srsra
      * srsue container
      * srsenb container

I take this tcpdump:
 
`sudo tcpdump -i any -w srs_attach.pcap`

on all interfaces of baremetal machine but I only see encrypted packets. Is there a way to setup a clear channel? If yes how to do it?

Thanks 

Michele

**Comment by ShubhamTatvamasi** [comment]
Hi Michele, you can just use the MME IP like this:
```bash
sudo tcpdump host 192.168.60.142 -i any -w srs_attach.pcap
```
Thanks

**Comment by michelelaporta** [comment]
Thanks now I see S1AP packets.
