### ISSUE TITLE
run srsRAN-demo in another machine

### ISSUE THREAD

**Issue by michelelaporta** [ShubhamTatvamasi/srsRAN-demo#4]
Hi Shubham,
is there a way to run srsRAN-demo in another machine instead of AGW?
Thanks
Michele

**Comment by ShubhamTatvamasi** [comment]
Hi [Michele](https://github.com/michelelaporta),
Yes, you can deploy srsRAN on another host. In that scenario, you just have to host the services using bridge mode for both AGW and srsRAN so they can communicate.
Thanks

**Comment by michelelaporta** [comment]
Thanks my current solution was running  srsRAN without vagrant but docker with net host on the same agw machine.
